config/routes.rb
Rails.application.routes.draw do
  root "kittens#index"

  resources :kittens
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
    validates :name, presence: true
    validates :age, presence: true, numericality: { greater_than: 0 }
    validates :cuteness, presence: true, numericality: { greater_than: 0, less_than: 6 }
    validates :softness, presence: true, numericality: { greater_than: 0, less_than: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to kitten_path(@kitten), notice: "Kitten created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      redirect_to kitten_path(@kitten), notice: "Kitten updated successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    redirect_to kittens_path, status: :see_other, alert: "Kitten deleted successfully"
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render "shared/form", kitten: @kitten %>

<%= link_to "Back", kitten_path(@kitten), class: "btn btn-secondary" %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<div class="row">
<% @kittens.each do |kitten| %>
    <div class="col-md-4">
        <h4><%= link_to kitten.name, kitten_path(kitten) %></h4>
        <p><%= "Age: #{kitten.age}" %></p>
    </div>
<% end %>
</div>

<%= link_to "Create New Kitten", new_kitten_path, class: "btn btn-primary" %>

app/views/kittens/new.html.erb
<h1>Create New Kitten</h1>

<%= render "shared/form", kitten: @kitten %>

<%= link_to "Back", kittens_path, class: "btn btn-secondary" %>

app/views/kittens/show.html.erb
<div class="container">
    <h1><%= @kitten.name %></h1>
    <p><%= "Age: #{@kitten.age}" %></p>
    <p><%= "Cuteness: #{@kitten.cuteness}" %></p>
    <p><%= "Softness: #{@kitten.softness}" %></p>
    
    <%= link_to "Back", kittens_path, class: "btn btn-primary" %>
    <%= link_to "Edit", edit_kitten_path(@kitten), class: "btn btn-warning" %>
    <%= link_to "Delete", kitten_path(@kitten), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Kittens" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>   

app/views/shared/_form.html.erb
<%= form_with model: kitten do |form| %>

    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <%= form.object.errors.full_messages.join(". ") %>
        </div>
    <% end %>

    <div class="mb-3">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>
    <div class="mb-3">
        <%= form.label :age %>
        <%= form.number_field :age %>
    </div>
    <div class="mb-3">
        <%= form.label :cuteness %>
        <%= form.number_field :cuteness %>
    </div>
    <div class="mb-3">
        <%= form.label :softness %>
        <%= form.number_field :softness %>
    </div>
    <div class="mb-3">
        <%= form.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>